---
title: "Creating PDF"
author: "Asela Wijeratne"
date: "5/3/2020"
output: pdf_document
pdf_document:
    citation_package: natbib
    df_print: kable
    fig_width: 3
    fig_height: 12
    fig_caption: true

    
toc: True
toc_depth: 4
number_sections: true
#LaTex options
fontsize: 12pt


bibliography: mycitations.bib
#csl: ieee.csl
---
# 1. Level-1 heading (A)
This is how I am going to cite my work [@R-base].

## 2. Level-2 heading (B)
my second citation [@Maetschke2014].

###3. Level-3 heading (C)
My third citation[@RazaghiMoghadam2020a].
```{r}
library(ggplot2)
dat <- data.frame(
  time = factor(c("Lunch","Dinner"), levels=c("Lunch","Dinner")),
  total_bill = c(14.89, 17.23)
)
knitr::kable(dat)
```

```{r, type="figure", echo=FALSE, fig.align='left', fig.cap="Look at this nice big sample"}
ggplot(data=dat, aes(x=time, y=total_bill)) +
  geom_bar(stat="identity")
```

####4. Level-4 heading (D)

```{r, type="figure", anchor="figure", echo=FALSE, fig.align='left', fig.cap="second figure"}
ggplot(data=dat, aes(x=time, y=total_bill)) +
  geom_bar(stat="identity")
```





# References

